- name: configure mysql server
  hosts: mysql
  become: yes
  tasks:
  - name: install mysql libraries
    ansible.builtin.pip:
    name: PyMySQL
    executable: pip3.9

  - name: mysql install
    ansible.builtin.package:
    name: mysql-server
    state: installed
  
  - name: start & enable mysql server
    ansible.builtin.service:
      name: mysql
      state: started
      enabled: yes
  
  - name : connect to mysql server
    community.mysql.mysqlinfo:
      login_user: root
      login_password: Webapp@1
      login_host: 172.31.90.14
    register: mysql_info
    ignore_errors: true
  
  - name: print output
    ansible.builtin.debug:
      msg: "mysql info: {{mysql_info}}"

  - name: setup root password
    ansible.builtin.command: "mysql_secure_installation --set-root-pass WEbapp@1 "
    when : mysql_info.filed is true

  



