- name: configure mysql server
  hosts: mysql
  become: yes
  vars:
      mysql_root_password: WebApp@1
      login_host: 172.31.90.14
  tasks:
  - name: install mysql libraries
    ansible.builtin.pip:
      name: '{{item}}'
      executable: pip3.9
    loop:
    - cryptography
    - PyMySQL

  - name: mysql install
    ansible.builtin.package:
      name: mysql-server
      state: installed
  
  - name: start & enable mysql server
    ansible.builtin.service:
      name: mysql
      state: started
      enabled: yes
  
  - name : connect to mysql server
    community.mysql.mysql_info:
      login_user: root
      login_password: "{{mysql_root_password}}"
      login_host: "{{login_host}}"
    register: mysql_info
    ignore_errors: true
  
  - name: print output
    ansible.builtin.debug:
      msg: "mysql info: {{ mysql_info }}"

  - name: setup MySQL root password
    ansible.builtin.command: "mysql_secure_installation --set-root-pass {{ mysql_root_password }}"
    when: mysql_info.failed is true
